[package]
name = "mcp_eeprom"
version = "0.1.0"
authors = ["Mattia Maldini <mattia512maldini@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-time = "0.10.0"
embedded-hal = "0.2"
